[package]
name = "easy-cache"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
tokio = { version = "1.25.0", features = ['full']}
serde = { version = "1.0.152", features = ['derive'] }
uuid = { version = "1.3.0", features = ['v4', 'fast-rng', 'macro-diagnostics'] }
